// WARNING: This file (defines.h) is automatically generated by Cmake. DO NOT EDIT
// WARNING: Any edit will be lost on running Cmake again.
// WARNING: Instead, do edit defines.h.in
/**
 * @file defines.h
 * @author Paolo Bosetti (paolo.bosetti@unitn.it)
 * @brief Userland driver for Mightex TCE-1304-U line CCD camera
 * 
 * General include file.
 * 
 * @version 0.2.2
 * @date 2021-06-04
 * 
 * @copyright Copyright (c) 2021
 */

/**
 * @mainpage Mightex1304 library
 * 
 * This library allow to acquire "images" (actually lines of pixels) from a 
 * Mightex TCE-1304-U CCD line camera. It relies on [libusb](http://libusb.info)
 * for talking to the device.
 */

#ifndef DEFINES_H
#define DEFINES_H
#ifndef _WIN32
#include <sys/param.h>
#endif
#ifdef __linux
#include <inttypes.h>
#endif

// Cmake-generated values:
#define GIT_VERSION_TAG "0.2.2"
#define GIT_COMMIT_HASH "0.2.2-11-gd53b114X"
#define CMAKE_PLATFORM "x86_64-apple-darwin20.5.0"
#define CMAKE_BUILD_TYPE "Release"

#endif
