name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true #enable LFS

    - name: Checkout LFS objects
      run: git lfs checkout # actually checkout stuff

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --long --dirty=X)
      shell: bash

    - name: SWIG
      run: swig -lua -c++ -o src/mightex_lua.cpp src/mightex.hh


    - uses: actions/upload-artifact@v2
      # Create a single artifact (zip folder) with binaries for 3 OSs
      with:
        name: mightex1304-${{env.BUILD_TYPE}}-${{steps.get_version.outputs.VERSION}}
        path: |
          src/*
    
